# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleID', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('DescriptionSEO', models.CharField(max_length=500)),
                ('KeywordsSEO', models.CharField(max_length=100)),
                ('AuthorSEO', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Class', models.IntegerField()),
                ('Lable', models.IntegerField()),
                ('PageView', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('CreateTime', models.DateTimeField()),
                ('UpdateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassID', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=20)),
                ('ClassAbstract', models.CharField(max_length=50)),
                ('Status', models.IntegerField()),
                ('CreateTime', models.DateTimeField()),
                ('UpdateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('LableID', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('LableName', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('CreateTime', models.DateTimeField()),
                ('UpdateTime', models.DateTimeField()),
            ],
        ),
    ]
