# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='Lable',
            field=models.CharField(max_length=20),
        ),
    ]
