# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170711_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('CookieID', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='CookieID')),
                ('CookieValue', models.CharField(max_length=50, verbose_name='Cookie\u503c')),
                ('CreateTime', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCount',
            fields=[
                ('DailyCountID', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='CookieID')),
                ('NewIPNum', models.IntegerField()),
                ('NewCookieNum', models.IntegerField()),
                ('ActiveIPNum', models.IntegerField()),
                ('ActiveCookieNum', models.IntegerField()),
                ('CreateTime', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('IPID', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='IPID')),
                ('IPValue', models.CharField(max_length=50, verbose_name='IP\u503c')),
                ('CreateTime', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleID',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='\u6587\u7ae0ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='AuthorSEO',
            field=models.CharField(max_length=20, verbose_name='SEO\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Class',
            field=models.CharField(max_length=20, verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='article',
            name='CreateTime',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='DescriptionSEO',
            field=models.CharField(max_length=500, verbose_name='SEO\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='article',
            name='KeywordsSEO',
            field=models.CharField(max_length=100, verbose_name='SEO\u5173\u952e\u5b57'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Lable',
            field=models.CharField(max_length=20, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='article',
            name='PageView',
            field=models.IntegerField(verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.IntegerField(verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='article',
            name='UpdateTime',
            field=models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassAbstract',
            field=models.CharField(max_length=50, verbose_name='\u7c7b\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassID',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='\u7c7bID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassName',
            field=models.CharField(max_length=20, verbose_name='\u7c7b\u540d'),
        ),
        migrations.AlterField(
            model_name='class',
            name='CreateTime',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='class',
            name='Status',
            field=models.IntegerField(verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='class',
            name='UpdateTime',
            field=models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lable',
            name='CreateTime',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lable',
            name='LableID',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='\u6807\u7b7eID'),
        ),
        migrations.AlterField(
            model_name='lable',
            name='LableName',
            field=models.CharField(max_length=20, verbose_name='\u6807\u7b7e\u540d'),
        ),
        migrations.AlterField(
            model_name='lable',
            name='Status',
            field=models.IntegerField(verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='lable',
            name='UpdateTime',
            field=models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
