# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='TimeLine',
            field=models.IntegerField(verbose_name='\u65f6\u95f4\u8f74'),
        ),
    ]
