# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170724_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lable',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Lable',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='LableID',
            new_name='LabelID',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='LableName',
            new_name='LabelName',
        ),
    ]
